# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 13:23
from __future__ import unicode_literals

import common.utils
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20180103_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='avatar',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url=b'/media/avatars/', location=b'/home/anton/vwrapperhome/boarddirector_dev_python/public/media/avatars'), upload_to=common.utils.avatar_upload_to),
        ),
    ]
