# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180411_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='send_invitations',
            field=models.BooleanField(default=False, verbose_name='send automatic email invitations for new users and meetings'),
        ),
    ]
