# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-20 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_send_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='enforce_2fa',
            field=models.BooleanField(default=False, verbose_name='enforce 2fa'),
        ),
    ]
