# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_enforce_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='enable_social_logins',
            field=models.BooleanField(default=True, verbose_name='enable social logins'),
        ),
        migrations.AlterField(
            model_name='account',
            name='send_notification',
            field=models.BooleanField(default=True, verbose_name='send email notifications'),
        ),
    ]
