# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_auto_20180314_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='downloadable',
            field=models.BooleanField(default=True),
        ),
    ]
