# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180411_2014'),
        ('documents', '0015_document_downloadable'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='hidden'),
        ),
        migrations.AddField(
            model_name='folder',
            name='special_field',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Discussion')], null=True, verbose_name='special fields'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set([('account', 'special_field'), ('parent', 'name')]),
        ),
    ]
