# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_auto_20180505_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrail',
            name='downloadable',
            field=models.BooleanField(default=True),
        ),
    ]
