# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170615_0445'),
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_name', models.CharField(max_length=255, verbose_name='feed name')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News', verbose_name='news')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
