# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_messagesnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='feed_name',
            field=models.CharField(default='', max_length=255, verbose_name='feed name'),
        ),
    ]
