# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_messages_feed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='member_receive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_receive', to='profiles.Membership', verbose_name='member receive'),
        ),
    ]
