# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0005_discussions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesnews',
            name='news',
        ),
        migrations.DeleteModel(
            name='MessagesNews',
        ),
    ]
