# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0006_auto_20180501_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='activity_id',
            field=models.CharField(max_length=255, null=True, verbose_name='activity'),
        ),
        migrations.AddField(
            model_name='messages',
            name='to',
            field=models.CharField(max_length=255, null=True, verbose_name='to_activity'),
        ),
    ]
