# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 04:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0008_messages_getstream_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='file_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), null=True, size=None),
        ),
    ]
