# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0009_messages_file_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussions',
            name='private',
            field=models.BooleanField(default=False, help_text='Private channel', verbose_name='private'),
        ),
    ]
