# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0010_discussions_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussions',
            name='auto',
            field=models.BooleanField(default=True, help_text='Auto channel', verbose_name='auto'),
        ),
    ]
