# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20180429_0823'),
        ('discussion', '0011_discussions_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussions',
            name='member_ids',
            field=models.ManyToManyField(to='profiles.Membership', verbose_name='member_ids'),
        ),
        migrations.AddField(
            model_name='discussions',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
    ]
