# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0012_auto_20180511_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussions',
            name='details',
            field=models.TextField(null=True, verbose_name='details'),
        ),
    ]
