# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0013_discussions_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListRequestsChannels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('getstream_info', models.TextField(null=True, verbose_name='getstream info')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='discussion.Discussions', verbose_name='discussion')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
