# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20180429_0823'),
        ('discussion', '0015_auto_20180525_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussions',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_id_member', to='profiles.Membership', verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='discussions',
            name='member_ids',
            field=models.ManyToManyField(related_name='member_ids_in_channel', to='profiles.Membership', verbose_name='member_ids'),
        ),
    ]
