# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0016_auto_20180526_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listrequestschannels',
            name='discussion',
            field=models.IntegerField(verbose_name='discussion id history'),
        ),
    ]
